#!/bin/sh
echo $1 $2
NAME=$1
FILE=$2
if [ -r "$FILE" ]
then SOURCEEXP="file=@$FILE"
elif [ `echo $FILE | grep '^http'` ]
then SOURCEEXP="contentURL=$FILE"
else SOURCEEXP="ILLEGAL SOURCE"
echo "No input found: $2"
exit 0
fi
BT=`cat token.txt`

curl -Ss -X PUT 'https://mscr-test.rahtiapp.fi/datamodel-api/v2/schemaFull' --header 'Accept: */*' --header 'User-Agent: Thunder Client (https://www.thunderclient.com)' --header 'Authorization: Bearer '$BT --form metadata="{ \"status\": \"DRAFT\", \"state\": \"DRAFT\", \"visibility\": \"PUBLIC\", \"namespace\": \"http://test.com\", \"versionLabel\": \"1\", \"label\": { \"en\": \"$NAME\" }, \"description\": { \"en\": \"string\" } , \"languages\": [\"en\"], \"format\": \"XSL\" }" --form $SOURCEEXP | jq

#'contentURL="https://gist.githubusercontent.com/iwasdavid/2b65c4259c284a3c910266c2f5a1e308/raw/90bf6972288545c2b329446c90820c79fecf3d73/sample.xsd"'


#'contentURL="http://rs.gbif.org/schema/eml-gbif-profile/1.1/eml-gbif-profile.xsd"'
