#!/bin/sh
# delete MSCR registered schema
# e.g. use ./apideleteschema PID1 PID2 PID3
# e.g. use ./apideleteschema `./apigetinfo | xargs`
#
echo DELETE $@
#NAME=$1
for PID do
echo "deleting $PID"
curl -Ss -X DELETE https://mscr-test.rahtiapp.fi/datamodel-api/v2/schema/$PID --header 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIwYjNiNjZmZS1iMWY4LTQ1YTctYmVjNi02YmQ3ZjAxM2I5OTciLCJleHAiOjE3MjgwNDc2NzQsImlhdCI6MTcxMjIzNjQ3NH0.CWHiJhpY13raAnWo2ZV8TpJl6pD-DAugYBg-JqgD_jVID8IGlNfvjPZNl3EUQ6ro-lRnRwEmgL6TYBBS3pHcmw' | jq
done

