#!/bin/sh
echo $1 $2
NAME=$1
FILE=$1
if [ -r "$FILE" ]
then SOURCEEXP="file=$FILE"
elif [ `echo $FILE | grep '^http:'` ]
then SOURCEEXP="contentURL=$FILE"
else SOURCEEXP="ILLEGAL SOURCE"
fi
echo $SOURCEEXP

